In [75]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [76]:
dataset = pd.read_csv("/Users/apple/Desktop/untitled folder/analytics_lab.csv")

In [77]:
dataset

S.no Stu.Reg.no       Q-1      Q-2       Q-3       Q-4       Q-5  \
0      1  20BCI7150         a        b         b         a         b   
1      2  20BCD7129         a        b         b         b         b   
2      3  20BCE7113         a        a         b         a         b   
3      4  20BCE7114         a        b         a         a         b   
4      5  20BCE7115         a        b         b         a         b   
5      6  20BCE7116         a        b         b         a         b   
6      7  20BCE7117         a        b         a         a         b   
7      8  20BCE7118         a        b         b         a         b   
8      9  20BCE7119         a        b         b         a         b   
9     10  20BCE7120         a        b         b         a         b   
10    11  20BCI7151         a        b         b         a         b   
11    12  20BCD7128         a        b         b         a         b   
12    13  20BCE7213         a        b         a         a         b   
13    14  20BCE7214         a        b         b         b         b   
14    15  20BCE7215         a        b         b         a         b   
15    16  20BCE7216         a        b         b         a         b   
16    17  20BCE7217         a        b         b         b         a   
17    18  20BCE7218         a        b         b         a         b   
18    19  20BCE7219         a        a         b         a         b   
19    20  20BCE7220         a        a         b         a         b   
20    21  20BCI7153         b        b         b         a         b   
21    22  20BCD7187         a        b         a         a         b   
22    23  20BCE7313         a        b         b         a         b   
23    24  20BCE7314         a        b         b         a         b   
24    25  20BCE7315         b        b         b         a         b   
25    26  20BCE7316         a        b         b         a         b   
26    27  20BCE7317         b        b         b         a         b   
27    28  20BCE7318         a        b         b         a         b   
28    29  20BCE7319         a        a         b         a         b   
29    30  20BCE7320         a        b         b         a         b   

        Score  Mood State  
0          77           0  
1          87           1  
2          79           0  
3          82           1  
4          89           1  
5          83           0  
6          84           0  
7          97           1  
8          91           1  
9          79           0  
10         79           0  
11         86           1  
12         71           0  
13         84           1  
14         91           1  
15         81           0  
16         82           0  
17         97           1  
18         91           1  
19         79           0  
20         77           0  
21         87           1  
22         89           0  
23         80           1  
24         86           1  
25         82           0  
26         84           0  
27         97           1  
28         99           1  
29         70           0

In [78]:
# input
x = dataset.iloc[:, 7].values
# output
y = dataset.iloc[:, 8].values


In [48]:
x


array([77, 87, 79, 82, 89, 83, 84, 97, 91, 79])

In [79]:
x = x.reshape(-1,1)

In [80]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 0)


In [81]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
X_train = sc_x.fit_transform(X_train) 
X_test = sc_x.transform(X_test)
  
print (X_train[0:5])

[[ 1.8481294 ]
 [ 0.71871699]
 [-0.12834232]
 [-0.26951887]
 [ 1.00107009]]


In [51]:
X_train

array([[79],
       [87],
       [84],
       [97],
       [82],
       [77],
       [83]])

In [82]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)


LogisticRegression(random_state=0)

In [83]:
y_pred = classifier.predict(X_test)

In [84]:
X_test

array([[-0.69304852],
       [ 2.1304825 ],
       [ 0.01283423],
       [-0.69304852],
       [ 0.01283423],
       [ 0.29518733],
       [ 1.8481294 ],
       [ 0.29518733]])

In [85]:
from sklearn.metrics import accuracy_score
print ("Accuracy : ", accuracy_score(y_test, y_pred))


Accuracy :  0.875


In [86]:
X_test

array([[-0.69304852],
       [ 2.1304825 ],
       [ 0.01283423],
       [-0.69304852],
       [ 0.01283423],
       [ 0.29518733],
       [ 1.8481294 ],
       [ 0.29518733]])

In [87]:
random = np.array([86,84,85])
random = random.reshape(-1,1)

In [88]:
random_test = sc_x.transform(random)

In [89]:
random_pred = classifier.predict(random)

In [90]:
random_pred

array([1, 1, 1])

In [91]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

print ("Confusion Matrix : \n", cm)


Confusion Matrix : 
 [[3 0]
 [1 4]]
